### PR TITLE
fix: highlight current show on schedule page

### LINKED ISSUE #134: Current show is not highlighted on Schedule page
There is some logic and CSS indicating that the currently playing show should be highlighted in the schedule, but that seems not to be the case.

### PR DESCRIPTION
**Pull request by kchenturtles**
closes #134

### CODE REVIEW

File: src/app/Schedule/SchedulePage.tsx
Comment (jsit) [inline src/app/Schedule/SchedulePage.tsx]: I think we don't need to define this here?

File: src/app/Schedule/SchedulePage.tsx [hunk 1]
```diff
@@ -118,10 +135,11 @@ export default function SchedulePage({ currentShow }: SchedulePageProps) {
     show: ScheduleShow,
     dayName: string,
   ): boolean => {
-    if (!currentShow) return false;
```
Comment (jsit) [inline src/app/Schedule/SchedulePage.tsx]: I think we can actually probably get rid of `currentShowRef`? I don't think it does anything...

**Review by jsit — CHANGES_REQUESTED** [review]

File: src/app/Schedule/SchedulePage.tsx [hunk 2]
```diff
@@ -34,13 +34,30 @@ export default function SchedulePage({ currentShow }: SchedulePageProps) {
   const headerHeight = useHeaderHeight();
 
   const [schedule, setSchedule] = useState<ScheduleResponse | null>(null);
+  const [currentShowTitle, setCurrentShowTitle] = useState<string | undefined>(
+    currentShow,
```
Comment (jsit) [inline src/app/Schedule/SchedulePage.tsx]: I actually think `currentShow` is never passed to this component. So we can remove this component's interface object, and set this to type `<string>`

**Review by jsit — APPROVED** [review]
